CREATE TABLE IF NOT EXISTS week_summary(
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  crewId INTEGER NOT NULL,
  startDate DATE,
  content TEXT
);

CREATE TABLE IF NOT EXISTS event(
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  weekSummaryId INTEGER NOT NULL,
  crewId INTEGER NOT NULL,
  dateTime DATETIME,
  title VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS event_resource(
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  eventId INTEGER NOT NULL,
  label VARCHAR(255),
  url VARCHAR(255)
);